### ISSUE TITLE
Fail to convert a multipage PDF to SVG files

### ISSUE THREAD

**Issue by sadqiang** [dawbarton/pdf2svg#20]
I want to convert a multipage PDF to SVG files.
Based on main page, I have to use "all"

`pdf2svg <input.pdf> <output.svg> "all"`

I just got one SVG file that corresponds to the last page of my PDF file.

What do I miss here?

**Comment by miishan** [comment]
You missed the naming convention here: just add %d (or other printf directive) into output name on the place of the page number.

**Comment by sadqiang** [comment]
Thank you sir!
