### ISSUE TITLE
ERROR @ line 5: <symbol> is not supported

### ISSUE THREAD

**Issue by xyang5987** [dawbarton/pdf2svg#30]
I don't know if this is the right place to ask this question. I made a TikZ figure in the pdf format and converted to the svg format. It is success. However, when I tried to load the svg file to android studio as drawable vector.  Android studio showed the error. My question is: 

Is there a way I can avoid this problem when I make convertion?

Thanks,

Xuefeng

**Comment by zvezdochiot** [comment]
@xyang5987 say:
>ERROR @ line 5:

Let me read the 5th line of you SVG.

**Comment by xyang5987** [comment]
<symbol overflow="visible" id="glyph0-0">

**Comment by xyang5987** [comment]
symbol overflow="visible" id="glyph0-0"

**Comment by xyang5987** [comment]
symbol overflow="visible" id="glyph0-0"
I removed "<" and ">" from the two ends.

**Comment by zvezdochiot** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by zvezdochiot** [comment]
`<symbol>` is standard element SVG: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol . `Android studio` is bad.

**Comment by xyang5987** [comment]
Since Android is used for mobile phones which don't have enough resource to deal with whole SVG standard, so they have to make some restrictions. I'll leave the solution here later when I resolve this problem. 

Thanks

**Comment by dawbarton** [comment]
You can try opening up the SVG in Inkscape then select everything and Edit -> Clone -> Unlink Clones recursively, followed by File -> Clean Up Document.

**Comment by zvezdochiot** [comment]
@dawbarton say:
>You can try opening up the SVG in Inkscape

Maybe make an additional utility for this?

**Comment by dawbarton** [comment]
> Maybe make an additional utility for this?

That's a lot of work for only a little gain, particularly when Inkscape already does it all. Unfortunately I don't have the time for that sort of thing.

**Comment by zvezdochiot** [comment]
@dawbarton say:
>That's a lot of work for only a little gain

I agree. But I expected an indication of an existing utility (if any), or the use of inkscape in cli.

**Comment by dawbarton** [comment]
> > That's a lot of work for only a little gain
> 
> I agree. But I expected an indication of an existing utility (if any), or the use of inkscape in cli.

That's true. I expect it's possible with the verb interface of Inkscape. I know it's been revamped for the latest version - I've not had any experience of it though.

**Comment by xyang5987** [comment]
Yeah, there are a few tools to support VectorDrawable, which supports all features from Tiny SVG 1.2 except for text. That's what I found. Basically, I can't use VectorDrawable. Thanks all.
