### ISSUE TITLE
CMYK PDF, but in PDF2SVG I get RGB SVG

### ISSUE THREAD

**Issue by Sukii** [dawbarton/pdf2svg#34]
Attached please find a CMYK PDF, but in PDF2SVG I get RGB SVG.

See also the following discussion:
https://community.adobe.com/t5/indesign/cc2020-indesign-svg-cmyk-color-support/td-p/10719039
https://community.adobe.com/t5/illustrator/how-can-i-export-an-svg-with-both-rgb-and-cmyk-colors/m-p/6050907

Suki
[CMYK-image.pdf](https://github.com/dawbarton/pdf2svg/files/6525782/CMYK-image.pdf)

**Comment by dawbarton** [comment]
Unfortunately PDF2SVG only works with RGB colours.
