### ISSUE TITLE
pdf2svg for Mac OSX

### ISSUE THREAD

**Issue by wanglongqi** [dawbarton/pdf2svg#6]
There are several tutorial to compile `pdf2svg` under Mac OSX, but I do not want homebrew or fink installed on my Mac. Thus, can anyone provide a Mac OSX binary of `pdf2svg`.

**Comment by wanglongqi** [comment]
I add a binary version of `pdf2svg` for Mac OSX [here](https://github.com/wanglongqi/WriteTeX/raw/master/Binaries/Mac/pdf2svg.tar.gz). Can some one check whether it works?

**Comment by seppestas** [comment]
@wanglongqi The link to the binary for Mac OSX/macOS seems to be dead. Can you tell me how I can install the dependencies on macOS (poppler-glib in particular).
